---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ .Values.project_name }}
spec:
  limits:
    - default:
        cpu: {{ .Values.default_cpu_limit }}
        memory: {{ .Values.default_mem_limit }}
        ephemeral-storage: {{ .Values.default_ephemeral_storage_limit }}
      defaultRequest:
        cpu: {{ .Values.default_cpu_request }}
        memory: {{ .Values.default_mem_request }}
        ephemeral-storage: {{ .Values.default_ephemeral_storage_request }}
      type: Container
